	              	  	                      	      APT::Periodic::Update-Package-Lists "1";
	              	  	                      	      APT::Periodic::Unattended-Upgrade "1";
	              	  	                      	      EOF
	              	  	                      	      dpkg-reconfigure -fnoninteractive unattended-upgrades || true

	              	  	                      	      # --- 2) Nameservers: ensure at least two responsive resolvers (NETW-2705)
	              	  	                      	      log "Ensuring at least two nameservers (adds Cloudflare & Quad9 as fallbacks if needed)..."
	              	  	                      	      add_resolv_conf_ns() {
	              	  	                      	      	  local file="/etc/resolv.conf"
	              	  	                      	      	    # Only touch if not a systemd-resolved stub; otherwise configure resolved.conf
	              	  	                      	      	      if [ -L "$file" ] && readlink -f "$file" | grep -q "systemd"; then
	              	  	                      	      	          log "Detected systemd-resolved stub. Configuring /etc/systemd/resolved.conf..."
	              	  	                      	      	              backup_file /etc/systemd/resolved.conf
	              	  	                      	      	                  # Keep any existing DNS= entries; append fallbacks if missing
	              	  	                      	      	                      if ! grep -Eq '^\s*DNS=' /etc/systemd/resolved.conf; then
	              	  	                      	      	                            sed -i '/^\[Resolve\]/a DNS=1.1.1.1 9.9.9.9' /etc/systemd/resolved.conf || echo -e "[Resolve]\nDNS=1.1.1.1 9.9.9.9" >> /etc/systemd/resolved.conf
	              	  	                      	      	                                fi
	              	  	                      	      	                                    if ! grep -Eq '^\s*FallbackDNS=' /etc/systemd/resolved.conf; then
	              	  	                      	      	                                          sed -i '/^\[Resolve\]/a FallbackDNS=1.0.0.1 149.112.112.112' /etc/systemd/resolved.conf
	              	  	                      	      	                                              fi
	              	  	                      	      	                                                  systemctl restart systemd-resolved || true
	              	  	                      	      	                                                    else
	              	  	                      	      	                                                        local file="/etc/resolv.conf"
	              	  	                      	      	                                                            # Avoid clobbering DHCP-managed resolv.conf that gets overwritten frequently
	              	  	                      	      	                                                                if grep -qi 'DO NOT EDIT' "$file"; then
	              	  	                      	      	                                                                      log "Skipping direct edit of $file (appears managed). Consider setting DNS via your network config."
	              	  	                      	      	                                                                          else
	              	  	                      	      	                                                                                backup_file "$file"
	              	  	                      	      	                                                                                      # Add secondary resolvers if fewer than 2 present
	              	  	                      	      	                                                                                            local count
	              	  	                      	      	                                                                                                  count=$(grep -E '^\s*nameserver\s+' "$file" | wc -l | tr -d ' ')
	              	  	                      	      	                                                                                                        if [ "$count" -lt 2 ]; then
	              	  	                      	      	                                                                                                                { echo "nameserver 1.1.1.1"; echo "nameserver 9.9.9.9"; } >> "$file"
	              	  	                      	      	                                                                                                                      fi
	              	  	                      	      	                                                                                                                          fi
	              	  	                      	      	                                                                                                                            fi
	              	  	                      	      	                                                                                                                            }
	              	  	                      	      	                                                                                                                            add_resolv_conf_ns

	              	  	                      	      	                                                                                                                            # --- 3) Postfix: hide banner + disable VRFY if Postfix present (MAIL-8818, MAIL-8820)
	              	  	                      	      	                                                                                                                            if command -v postconf >/dev/null 2>&1; then
	              	  	                      	      	                                                                                                                              log "Hardening Postfix banner and disabling VRFY..."
	              	  	                      	      	                                                                                                                                backup_file /etc/postfix/main.cf
	              	  	                      	      	                                                                                                                                  postconf -e 'smtpd_banner=$myhostname ESMTP'       # remove OS/software details
	              	  	                      	      	                                                                                                                                    postconf -e 'disable_vrfy_command=yes'             # turn off VRFY
	              	  	                      	      	                                                                                                                                      systemctl reload postfix || true
	              	  	                      	      	                                                                                                                                      else
	              	  	                      	      	                                                                                                                                        log "Postfix not detected; skipping MAIL-8818/8820."
	              	  	                      	      	                                                                                                                                        fi

	              	  	                      	      	                                                                                                                                        # --- 4) login.defs: password policy & umask (AUTH-9282/9286/9328, AUTH-9230)
	              	  	                      	      	                                                                                                                                        log "Tweaking /etc/login.defs for sane password/umask defaults..."
	              	  	                      	      	                                                                                                                                        LOGIN_DEFS="/etc/login.defs"
	              	  	                      	      	                                                                                                                                        backup_file "$LOGIN_DEFS"
	              	  	                      	      	                                                                                                                                        # Set or update values
	              	  	                      	      	                                                                                                                                        declare -A defs=(
	              	  	                      	      	                                                                                                                                        	  [PASS_MIN_DAYS]="1"
	              	  	                      	      	                                                                                                                                        	    [PASS_MAX_DAYS]="90"
	              	  	                      	      	                                                                                                                                        	      [PASS_WARN_AGE]="14"
	              	  	                      	      	                                                                                                                                        	        [UMASK]="027"
	              	  	                      	      	                                                                                                                                        	          [SHA_CRYPT_MIN_ROUNDS]="10000"
	              	  	                      	      	                                                                                                                                        	            [SHA_CRYPT_MAX_ROUNDS]="50000"
	              	  	                      	      	                                                                                                                                        	            )
	              	  	                      	      	                                                                                                                                        	            for k in "${!defs[@]}"; do
	              	  	                      	      	                                                                                                                                        	              if grep -Eq "^\s*${k}\b" "$LOGIN_DEFS"; then
	              	  	                      	      	                                                                                                                                        	                  sed -ri "s|^\s*(${k})\s+.*|\1 ${defs[$k]}|g" "$LOGIN_DEFS"
	              	  	                      	      	                                                                                                                                        	                    else
	              	  	                      	      	                                                                                                                                        	                        echo "$k ${defs[$k]}" >> "$LOGIN_DEFS"
	              	  	                      	      	                                                                                                                                        	                          fi
	              	  	                      	      	                                                                                                                                        	                          done


	              	  	                      	      	                                                                                                                                        	                          # --- 6) Login banners (BANN-7126/7130)
	              	  	                      	      	                                                                                                                                        	                          log "Adding legal login banners to /etc/issue and /etc/issue.net..."
	              	  	                      	      	                                                                                                                                        	                          for f in /etc/issue /etc/issue.net; do
	              	  	                      	      	                                                                                                                                        	                            backup_file "$f"
	              	  	                      	      	                                                                                                                                        	                              cat > "$f" << "EOF"
																																													
	              	  	                      	      	                                                                                                                                        	                              Authorized access only. Disconnect immediately if you are not an authorized user.
	              	  	                      	      	                                                                                                                                        	                              All activities may be monitored and reported.
	              	  	                      	      	                                                                                                                                        	                              EOF
	              	  	                      	      	                                                                                                                                        	                              done

	              	  	                      	      	                                                                                                                                        	                              # --- 7) Fail2ban: basic sshd jail (DEB-0880)
	              	  	                      	      	                                                                                                                                        	                              log "Ensuring a basic Fail2Ban sshd jail..."
	              	  	                      	      	                                                                                                                                        	                              JAIL_LOCAL="/etc/fail2ban/jail.d/ssh-hardening.local"
	              	  	                      	      	                                                                                                                                        	                              backup_file "$JAIL_LOCAL"
	              	  	                      	      	                                                                                                                                        	                              mkdir -p /etc/fail2ban/jail.d
	              	  	                      	      	                                                                                                                                        	                              cat > "$JAIL_LOCAL" <<'EOF'
	              	  	                      	      	                                                                                                                                        	                              [sshd]
	              	  	                      	      	                                                                                                                                        	                              enabled = true
	              	  	                      	      	                                                                                                                                        	                              maxretry = 5
	              	  	                      	      	                                                                                                                                        	                              findtime = 10m
	              	  	                      	      	                                                                                                                                        	                              bantime = 1h
	              	  	                      	      	                                                                                                                                        	                              EOF
	              	  	                      	      	                                                                                                                                        	                              systemctl restart fail2ban || true

	              	  	                      	      	                                                                                                                                        	                              # --- 8) OPTIONAL: SSH hardening (SSH-7408) – enable by exporting APPLY_SSH_HARDEN=1
	              	  	                      	      	                                                                                                                                        	                              if [ "${APPLY_SSH_HARDEN:-0}" = "1" ]; then
	              	  	                      	      	                                                                                                                                        	                                if [ -f /etc/ssh/sshd_config ]; then
	              	  	                      	      	                                                                                                                                        	                                    log "Applying SSH hardening (you enabled APPLY_SSH_HARDEN=1)..."
	              	  	                      	      	                                                                                                                                        	                                        SSHD="/etc/ssh/sshd_config"
	              	  	                      	      	                                                                                                                                        	                                            backup_file "$SSHD"
	              	  	                      	      	                                                                                                                                        	                                                # Ensure key-value with yes/no or numeric values
	              	  	                      	      	                                                                                                                                        	                                                    set_kv() {
	              	  	                      	      	                                                                                                                                        	                                                    	      local key="$1" val="$2"
	              	  	                      	      	                                                                                                                                        	                                                    	            if grep -Eq "^\s*#?\s*${key}\b" "$SSHD"; then
	              	  	                      	      	                                                                                                                                        	                                                    	                    sed -ri "s|^\s*#?\s*(${key})\s+.*|\1 ${val}|g" "$SSHD"
	              	  	                      	      	                                                                                                                                        	                                                    	                          else
	              	  	                      	      	                                                                                                                                        	                                                    	                                  echo "${key} ${val}" >> "$SSHD"
	              	  	                      	      	                                                                                                                                        	                                                    	                                        fi
	              	  	                      	      	                                                                                                                                        	                                                    	                                            }
	              	  	                      	      	                                                                                                                                        	                                                    	                                                set_kv "LogLevel" "VERBOSE"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                    set_kv "MaxAuthTries" "3"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                        set_kv "ClientAliveCountMax" "2"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                            set_kv "MaxSessions" "2"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                set_kv "Compression" "no"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                    set_kv "TCPKeepAlive" "no"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                        set_kv "X11Forwarding" "no"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                            set_kv "AllowTcpForwarding" "no"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                set_kv "AllowAgentForwarding" "no"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                    # Do not lock you out: keep PubkeyAuthentication default and don't touch ports here.
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                        sshd -t
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                            systemctl reload ssh || systemctl restart ssh
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                              else
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                  log "No /etc/ssh/sshd_config found; skipping SSH hardening."
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                    fi
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                    else
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      log "SSH hardening not applied (set APPLY_SSH_HARDEN=1 to enable)."
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      fi

	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      # --- 9) Debsums database init (PKGS-7370/DEB-0875)
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      log "Initializing debsums metadata (this may take a bit)..."
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      debsums_init() {
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  dpkg-query -W -f='${Package}\n' | xargs -r -n1 debsums -s >/dev/null 2>&1 || true
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  }
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  debsums_init

	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  # --- 10) nudge to update packages (PKGS-7392/7420) – do NOT dist-upgrade automatically here
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  log "Performing a safe upgrade (no dist-upgrade)..."
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  apt-get upgrade -y

	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  log "All done. Backups saved in: $BACKUP_DIR"
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	  echo "Re-run Lynis to verify improvements."
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      	 
	              	  	                      	      	                                                                                                                                        	                                                    	                                                                                                      }
	              	  	                      	      	                                                                                                                                        	                                                    }
	              	  	                      	      	                                                                                                                                        )
	              	  	                      	      }
	              	  	                      }
	              	  }
	              }
}]
